// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqMSIOpqFBwdx4t83PPmOLA9PYA5nHsA',
    appId: '1:770385364338:web:1eadc6faf68bfd26a689eb',
    messagingSenderId: '770385364338',
    projectId: 'prost-33c19',
    authDomain: 'prost-33c19.firebaseapp.com',
    storageBucket: 'prost-33c19.firebasestorage.app',
    measurementId: 'G-GWB6HD2GJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8sPJ-2kjqPTex_uYgWH164R548YGUPY',
    appId: '1:770385364338:android:279a4bed667d19e1a689eb',
    messagingSenderId: '770385364338',
    projectId: 'prost-33c19',
    storageBucket: 'prost-33c19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknDGXkvisYhGzn7Eu3Z097-bXr_PjwJk',
    appId: '1:770385364338:ios:fa6af301868f7e19a689eb',
    messagingSenderId: '770385364338',
    projectId: 'prost-33c19',
    storageBucket: 'prost-33c19.firebasestorage.app',
    iosBundleId: 'com.example.prost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDknDGXkvisYhGzn7Eu3Z097-bXr_PjwJk',
    appId: '1:770385364338:ios:fa6af301868f7e19a689eb',
    messagingSenderId: '770385364338',
    projectId: 'prost-33c19',
    storageBucket: 'prost-33c19.firebasestorage.app',
    iosBundleId: 'com.example.prost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOqMSIOpqFBwdx4t83PPmOLA9PYA5nHsA',
    appId: '1:770385364338:web:fabf89a41104a1b0a689eb',
    messagingSenderId: '770385364338',
    projectId: 'prost-33c19',
    authDomain: 'prost-33c19.firebaseapp.com',
    storageBucket: 'prost-33c19.firebasestorage.app',
    measurementId: 'G-70Q1FQJED4',
  );
}
